export const longText = `As used in this chapter, unless the context requires a different meaning:
"Association" means the same as that term is defined in § 55-528.
"Board" means the Common Interest Community Board.
"Common interest community" means the same as that term is defined in § 55-528; provided that for the purposes of this chapter only, a common interest community shall not include any time-share project registered pursuant to the Virginia Real Estate Time-Share Act (§ 55-360 et seq.) or any additional land that is a part of such registration.
"Common interest community manager" means a person or business entity, including but not limited to a partnership, association, corporation, or limited liability company, who, for compensation or valuable consideration, provides management services to a common interest community.
"Declaration" means the same as that term is defined in § 55-528.
"Governing board" means the governing board of an association, including the executive organ of a condominium unit owners' association, the executive board of a cooperative proprietary lessees' association, and the board of directors or other governing body of a property owners' association.
"Lot" means the same as that term is defined in § 55-528.
"Management services" means (i) acting with the authority of an association in its business, legal, financial, or other transactions with association members and nonmembers; (ii) executing the resolutions and decisions of an association or, with the authority of the association, enforcing the rights of the association secured by statute, contract, covenant, rule, or bylaw; (iii) collecting, disbursing, or otherwise exercising dominion or control over money or other property belonging to an association; (iv) preparing budgets, financial statements, or other financial reports for an association; (v) arranging, conducting, or coordinating meetings of an association or the governing body of an association; (vi) negotiating contracts or otherwise coordinating or arranging for services or the purchase of property and goods for or on behalf of an association; or (vii) offering or soliciting to perform any of the aforesaid acts or services on behalf of an association.
As used in this chapter, unless the context requires a different meaning:
TESTMATCH
"Association" means the same as that term is defined in § 55-528.
"Board" means the Common Interest Community Board.
"Common interest community" means the same as that term is defined in § 55-528; provided that for the purposes of this chapter only, a common interest community shall not include any time-share project registered pursuant to the Virginia Real Estate Time-Share Act (§ 55-360 et seq.) or any additional land that is a part of such registration.
"Common interest community manager" means a person or business entity, including but not limited to a partnership, association, corporation, or limited liability company, who, for compensation or valuable consideration, provides management services to a common interest community.
TESTMATCH
"Declaration" means the same as that term is defined in § 55-528.
"Governing board" means the governing board of an association, including the executive organ of a condominium unit owners' association, the executive board of a cooperative proprietary lessees' association, and the board of directors or other governing body of a property owners' association.
"Lot" means the same as that term is defined in § 55-528.
"Management services" means (i) acting with the authority of an association in its business, legal, financial, or other transactions with association members and nonmembers; (ii) executing the resolutions and decisions of an association or, with the authority of the association, enforcing the rights of the association secured by statute, contract, covenant, rule, or bylaw; (iii) collecting, disbursing, or otherwise exercising dominion or control over money or other property belonging to an association; (iv) preparing budgets, financial statements, or other financial reports for an association; (v) arranging, conducting, or coordinating meetings of an association or the governing body of an association; (vi) negotiating contracts or otherwise coordinating or arranging for services or the purchase of property and goods for or on behalf of an association; or (vii) offering or soliciting to perform any of the aforesaid acts or services on behalf of an association.
As used in this chapter, unless the context requires a different meaning:
TESTMATCH
"Association" means the same as that term is defined in § 55-528.
"Board" means the Common Interest Community Board.
"Common interest community" means the same as that term is defined in § 55-528; provided that for the purposes of this chapter only, a common interest community shall not include any time-share project registered pursuant to the Virginia Real Estate Time-Share Act (§ 55-360 et seq.) or any additional land that is a part of such registration.
"Common interest community manager" means a person or business entity, including but not limited to a partnership, association, corporation, or limited liability company, who, for compensation or valuable consideration, provides management services to a common interest community.
"Declaration" means the same as that term is defined in § 55-528.
"Governing board" means the governing board of an association, including the executive organ of a condominium unit owners' association, the executive board of a cooperative proprietary lessees' association, and the board of directors or other governing body of a property owners' association.
"Lot" means the same as that term is defined in § 55-528.
TESTMATCH
"Management services" means (i) acting with the authority of an association in its business, legal, financial, or other transactions with association members and nonmembers; (ii) executing the resolutions and decisions of an association or, with the authority of the association, enforcing the rights of the association secured by statute, contract, covenant, rule, or bylaw; (iii) collecting, disbursing, or otherwise exercising dominion or control over money or other property belonging to an association; (iv) preparing budgets, financial statements, or other financial reports for an association; (v) arranging, conducting, or coordinating meetings of an association or the governing body of an association; (vi) negotiating contracts or otherwise coordinating or arranging for services or the purchase of property and goods for or on behalf of an association; or (vii) offering or soliciting to perform any of the aforesaid acts or services on behalf of an association.
As used in this chapter, unless the context requires a different meaning:
"Association" means the same as that term is defined in § 55-528.
"Board" means the Common Interest Community Board.
"Common interest community" means the same as that term is defined in § 55-528; provided that for the purposes of this chapter only, a common interest community shall not include any time-share project registered pursuant to the Virginia Real Estate Time-Share Act (§ 55-360 et seq.) or any additional land that is a part of such registration.
"Common interest community manager" means a person or business entity, including but not limited to a partnership, association, corporation, or limited liability company, who, for compensation or valuable consideration, provides management services to a common interest community.
"Declaration" means the same as that term is defined in § 55-528.
"Governing board" means the governing board of an association, including the executive organ of a condominium unit owners' association, the executive board of a cooperative proprietary lessees' association, and the board of directors or other governing body of a property owners' association.
"Lot" means the same as that term is defined in § 55-528.
TESTMATCH
"Management services" means (i) acting with the authority of an association in its business, legal, financial, or other transactions with association members and nonmembers; (ii) executing the resolutions and decisions of an association or, with the authority of the association, enforcing the rights of the association secured by statute, contract, covenant, rule, or bylaw; (iii) collecting, disbursing, or otherwise exercising dominion or control over money or other property belonging to an association; (iv) preparing budgets, financial statements, or other financial reports for an association; (v) arranging, conducting, or coordinating meetings of an association or the governing body of an association; (vi) negotiating contracts or otherwise coordinating or arranging for services or the purchase of property and goods for or on behalf of an association; or (vii) offering or soliciting to perform any of the aforesaid acts or services on behalf of an association.
As used in this chapter, unless the context requires a different meaning:
"Association" means the same as that term is defined in § 55-528.
"Board" means the Common Interest Community Board.
"Common interest community" means the same as that term is defined in § 55-528; provided that for the purposes of this chapter only, a common interest community shall not include any time-share project registered pursuant to the Virginia Real Estate Time-Share Act (§ 55-360 et seq.) or any additional land that is a part of such registration.
"Common interest community manager" means a person or business entity, including but not limited to a partnership, association, corporation, or limited liability company, who, for compensation or valuable consideration, provides management services to a common interest community.
"Declaration" means the same as that term is defined in § 55-528.
"Governing board" means the governing board of an association, including the executive organ of a condominium unit owners' association, the executive board of a cooperative proprietary lessees' association, and the board of directors or other governing body of a property owners' association.

TESTMATCH
"Lot" means the same as that term is defined in § 55-528.
"Management services" means (i) acting with the authority of an association in its business, legal, financial, or other transactions with association members and nonmembers; (ii) executing the resolutions and decisions of an association or, with the authority of the association, enforcing the rights of the association secured by statute, contract, covenant, rule, or bylaw; (iii) collecting, disbursing, or otherwise exercising dominion or control over money or other property belonging to an association; (iv) preparing budgets, financial statements, or other financial reports for an association; (v) arranging, conducting, or coordinating meetings of an association or the governing body of an association; (vi) negotiating contracts or otherwise coordinating or arranging for services or the purchase of property and goods for or on behalf of an association; or (vii) offering or soliciting to perform any of the aforesaid acts or services on behalf of an association.
As used in this chapter, unless the context requires a different meaning:
"Association" means the same as that term is defined in § 55-528.
"Board" means the Common Interest Community Board.
"Common interest community" means the same as that term is defined in § 55-528; provided that for the purposes of this chapter only, a common interest community shall not include any time-share project registered pursuant to the Virginia Real Estate Time-Share Act (§ 55-360 et seq.) or any additional land that is a part of such registration.
"Common interest community manager" means a person or business entity, including but not limited to a partnership, association, corporation, or limited liability company, who, for compensation or valuable consideration, provides management services to a common interest community.
BOOOOOPS
"Declaration" means the same as that term is defined in § 55-528.
"Governing board" means the governing board of an association, including the executive organ of a condominium unit owners' association, the executive board of a cooperative proprietary lessees' association, and the board of directors or other governing body of a property owners' association.
"Lot" means the same as that term is defined in § 55-528.
"Management services" means (i) acting with the authority of an association in its business, legal, financial, or other transactions with association members and nonmembers; (ii) executing the resolutions and decisions of an association or, with the authority of the association, enforcing the rights of the association secured by statute, contract, covenant, rule, or bylaw; (iii) collecting, disbursing, or otherwise exercising dominion or control over money or other property belonging to an association; (iv) preparing budgets, financial statements, or other financial reports for an association; (v) arranging, conducting, or coordinating meetings of an association or the governing body of an association; (vi) negotiating contracts or otherwise coordinating or arranging for services or the purchase of property and goods for or on behalf of an association; or (vii) offering or soliciting to perform any of the aforesaid acts or services on behalf of an association.

ENDOFTEXT
`
